name: Lint, Typecheck, & Build

on:
  push:
  pull_request:
    branches: ['main']

jobs:
  lintAndBuild:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]

    name: Lint, Typecheck, & Build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.14.x
          cache: npm

      - name: NPM Install
        run: npm clean-install

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: node scripts/build.mjs

      - name: Package
        run: npx electron-builder --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            releases/GimbalGhost.*
            releases/latest*.yml
